### ISSUE TITLE
link to paper is defunct

### ISSUE THREAD

**Issue by akavel** [dgryski/go-failure#1]
proposed alternatives:

http://hdl.handle.net/10119/4784 ("Please use this identifier to cite or link to this item", via below) 

https://dspace.jaist.ac.jp/dspace/bitstream/10119/4784/1/IS-RR-2004-010.pdf (via Google Scholar)

http://web.archive.org/web/20150429133556/http://ddg.jaist.ac.jp/pub/HDY+04.pdf (web.archive.org)

also, please add the title of the paper ("The φ Accrual Failure Detector") in the godoc, to make it easier to google in case all above links rot in future.

**Comment by dgryski** [comment]
Thanks
